In [ ]:
# Numpy- is a fundamental package for scientific computing in python.It is a python library that provides multidimensional array.

In [ ]:
# Arrays- a data structure for storing homogenous data. All the elements are of same type.

In [ ]:
import numpy as np

In [ ]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.11/dist-packages/numpy/version.py'>

In [ ]:
# Numpy knows what is pi value

np.pi

3.141592653589793

In [ ]:
# Arrays can be created with numpy.array()

a= np.array([1,2,3,4])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
# Shape of numpy array (columns,rows)

a.shape

(4,)

In [ ]:
# Check dimension

a.ndim

1

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
# accessing elements

a[0]

np.int64(1)

In [ ]:
a[1]

np.int64(2)

In [ ]:
a[2:4]

array([3, 4])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a[:-1]

array([1, 2, 3])

In [ ]:
a[0:2]

array([1, 2])

In [ ]:
a[1:3] # end range n-1

array([2, 3])

In [ ]:
# Lets create a 2 dimensional array

b=np.array([[1,2,3],[4,5,6]])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b.ndim

2

In [ ]:
b.shape

(2, 3)

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b[0]

array([1, 2, 3])

In [ ]:
b[1]

array([4, 5, 6])

In [ ]:
b[0][2]

np.int64(3)

In [ ]:
b[1][0]

np.int64(4)

In [ ]:
# Creating 3 dimensional array

c= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
type(c)

numpy.ndarray

In [ ]:
c.shape

(3, 3)

In [ ]:
c.ndim

2

In [ ]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
c[2]

array([7, 8, 9])

In [ ]:
# Iwant to access 4

c[1][0]

np.int64(4)

In [ ]:
# I want to access 8

c[2][1]

np.int64(8)

In [ ]:
np.array([1,2,3,7]*3)

array([1, 2, 3, 7, 1, 2, 3, 7, 1, 2, 3, 7])

In [ ]:
# Repeat

np.repeat([2,3,4,5],3)

array([2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [ ]:
np.repeat([2,3,4,5],2)

array([2, 2, 3, 3, 4, 4, 5, 5])

In [ ]:
# 3 Dimensional array

Array= np.array([[[1, 2, 3], [11, 13, 14], [21, 22, 23]],
                 [[4, 5, 6], [15, 16, 17], [24, 25, 26]],
                 [[7, 8, 9], [18, 19, 20], [27, 28, 29]]])

In [ ]:
Array

array([[[ 1,  2,  3],
        [11, 13, 14],
        [21, 22, 23]],

       [[ 4,  5,  6],
        [15, 16, 17],
        [24, 25, 26]],

       [[ 7,  8,  9],
        [18, 19, 20],
        [27, 28, 29]]])

In [ ]:
type(Array)

numpy.ndarray

In [ ]:
Array.shape

(3, 3, 3)

In [ ]:
Array.ndim

3

In [ ]:
Array

array([[[ 1,  2,  3],
        [11, 13, 14],
        [21, 22, 23]],

       [[ 4,  5,  6],
        [15, 16, 17],
        [24, 25, 26]],

       [[ 7,  8,  9],
        [18, 19, 20],
        [27, 28, 29]]])

In [ ]:
Array[0][0][0]

np.int64(1)

In [ ]:
# iwant to extracct 4

Array[1][0][0]

np.int64(4)

In [ ]:
# I want to extract 18

Array[2][1][0]

np.int64(18)

In [ ]:
Array[1][1:]

array([[15, 16, 17],
       [24, 25, 26]])

In [ ]:
Array

array([[[ 1,  2,  3],
        [11, 13, 14],
        [21, 22, 23]],

       [[ 4,  5,  6],
        [15, 16, 17],
        [24, 25, 26]],

       [[ 7,  8,  9],
        [18, 19, 20],
        [27, 28, 29]]])

In [ ]:
Array[1][:2]

array([[ 4,  5,  6],
       [15, 16, 17]])

In [ ]:
# Create an array with one's

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Create an array with zeros

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Random numbers within an array

np.random.random(5)

array([0.68703546, 0.77913655, 0.7654157 , 0.76254479, 0.55460248])

In [ ]:
R= np.random.random(20)

R

array([0.97693287, 0.74198152, 0.09011745, 0.88347475, 0.42542355,
       0.45103327, 0.90893749, 0.83267862, 0.34337576, 0.70434483,
       0.30577086, 0.22070837, 0.1668578 , 0.36323856, 0.66216599,
       0.0335644 , 0.29719247, 0.97820567, 0.34272815, 0.59951777])

In [ ]:
# Empty array returns garbage value

np.empty(30)

array([4.78912501e-315, 0.00000000e+000, 5.38670379e+228, 2.47085366e-259,
       6.01347002e-154, 5.02801768e+223, 2.60987680e+180, 6.78844589e+199,
       5.83439515e+252, 3.80985847e+180, 9.30860854e+199, 4.75114180e+233,
       1.28624334e+248, 5.98181683e-154, 4.18206079e+180, 3.80985847e+180,
       2.66532288e-260, 6.01347002e-154, 8.26735752e+140, 2.31274374e-152,
       6.37852839e+170, 8.91101592e+252, 3.67591406e+228, 5.98189486e-154,
       6.01347002e-154, 1.96632065e-153, 5.39066223e+005, 6.01347002e-154,
       1.35488333e+243, 6.47603224e+170])

In [ ]:
# Creating matrics

np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# using random function create a matrix

np.random.random((3,2))

array([[0.57061965, 0.93047105],
       [0.93824255, 0.85096292],
       [0.83029918, 0.59457057]])

In [ ]:
# How to create only diagonally filled matrix

data=np.eye(5)

data

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Array arithematic

data= np.array([1,2])

data

array([1, 2])

In [ ]:
ones= np.ones(2)

ones

array([1., 1.])

In [ ]:
data + ones

array([2., 3.])

In [ ]:
# Multiplication

data*ones

array([1., 2.])

In [ ]:
# Division

data/ones

array([1., 2.])

In [ ]:
# subtraction

data-ones

array([0., 1.])

In [ ]:
# Multiply an array with a specific number

data * 1.5

array([1.5, 3. ])

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])

a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
b = np.array([[1,1]])
b

array([[1, 1]])

In [ ]:
a+b

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#  Can we find max

a.max()

np.int64(6)

In [ ]:
data

array([1, 2])

In [ ]:
# Min value

data.min()

np.int64(1)

In [ ]:
# Average

average=data.mean()

average

np.float64(1.5)

In [ ]:
# Std dev

data.std()

np.float64(0.5)

In [ ]:
data =np.array([[1,2],[5,3],[4,6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [ ]:
data.max()

np.int64(6)

In [ ]:
data.mean()

np.float64(3.5)

In [ ]:
# I want to print the sum

data.sum()

np.int64(21)

In [ ]:
# I want to calculate around a particular axis

np.sum(data,axis=0)

array([10, 11])

In [ ]:
np.max(data,axis=0)

array([5, 6])

In [ ]:
# Variance

data.var()

np.float64(2.9166666666666665)

In [ ]:
# Variance along the axis

np.var(data,axis=0)

array([2.88888889, 2.88888889])

In [ ]:
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [ ]:
# Square root of a function

np.sqrt(data)

array([[1.        , 1.41421356],
       [2.23606798, 1.73205081],
       [2.        , 2.44948974]])

In [ ]:
import math

In [ ]:
list= range(25)
roots=[]

for i in list:
  roots.append(math.sqrt(i))
  roots

In [ ]:
roots

[0.0,
 1.0,
 1.4142135623730951,
 1.7320508075688772,
 2.0,
 2.23606797749979,
 2.449489742783178,
 2.6457513110645907,
 2.8284271247461903,
 3.0,
 3.1622776601683795,
 3.3166247903554,
 3.4641016151377544,
 3.605551275463989,
 3.7416573867739413,
 3.872983346207417,
 4.0,
 4.123105625617661,
 4.242640687119285,
 4.358898943540674,
 4.47213595499958,
 4.58257569495584,
 4.69041575982343,
 4.795831523312719,
 4.898979485566356]

In [ ]:
# Sqrt in an array

array=np.arange(25)

roots=np.sqrt(array)

roots

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [ ]:
# Transpose

data= np.array([[1,2,3],[4,5,6],[7,8,9]])

data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
data.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
# Function Arange

m= np.arange(3,15)

m

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# Step up in range function

m=np.arange(3,15,2)

m

array([ 3,  5,  7,  9, 11, 13])

In [ ]:
# Full

np.full(5,12)

array([12, 12, 12, 12, 12])

In [ ]:
# Slice

arr_slice=np.array([[1,2,3],[4,5,6],[7,8,9]])

arr_slice

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_slice[0]

array([1, 2, 3])

In [ ]:
arr_slice[1]

array([4, 5, 6])

In [ ]:
arr_slice[1]=[1]

In [ ]:
arr_slice

array([[1, 2, 3],
       [1, 1, 1],
       [7, 8, 9]])

In [ ]:
a= np.array(42)
b= np.array([1,2,3,4,5])
c= np.array([[1,2,3],[4,5,6]])
d= np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [ ]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
Array= np.array([1,2,3])

In [ ]:
List= [1,2,3]

In [ ]:
type(Array)

numpy.ndarray

In [ ]:
type(List)

list

In [ ]:
# Lets multiply both with 2

print(Array*2)
print(List*2)

[2 4 6]
[1, 2, 3, 1, 2, 3]


In [ ]:
# leng of both variable

len(Array)

3

In [ ]:
len(List)

3

In [ ]:
# Shape

Array.shape

(3,)

In [ ]:
List.shape

AttributeError: 'list' object has no attribute 'shape'

In [ ]:
# Addittion

List_1 = [1,2,3]

List_2= [4,5,6]

List_1 + List_2

[1, 2, 3, 4, 5, 6]

In [ ]:
Array_1 = np.array([1,2,3])

Array_2 = np.array([4,5,6])

Array_1 + Array_2

array([5, 7, 9])